# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Create test users
      become: true
      ansible.builtin.user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: true
      with_items:
        - test_usr
        - test_usr2
        - test_usr3

    - name: Include package manager specific vars
      with_first_found:
        - '../../vars/pkg-mgr/{{ ansible_pkg_mgr }}.yml'
        - ../../vars/pkg-mgr/default.yml
      ansible.builtin.include_vars: '{{ item }}'

    - name: Install extension cli dependencies
      ansible.builtin.package:
        name: '{{ visual_studio_code_extensions_dependencies }}'
        state: present

    - name: Import VS Code RPM key (SUSE)
      ansible.builtin.rpm_key:
        state: present
        key: 'https://packages.microsoft.com/keys/microsoft.asc'
      when: "ansible_os_family == 'Suse'"

    - name: Install VS Code repo (SUSE)
      community.general.zypper_repository:
        name: Visual Studio Code
        repo: 'https://packages.microsoft.com/yumrepos/vscode'
        state: present
      when: "ansible_os_family == 'Suse'"

    - name: Install VS Code
      become: true
      ansible.builtin.package:
        name: code
        state: present
      register: vscode_install

    - name: Install VS Code Insiders (zypper)
      become: true
      ansible.builtin.package:
        name: code-insiders
        state: present
      register: vscode_insiders_install
      when: "ansible_pkg_mgr == 'zypper'"

    - name: Download VS Code RPM
      become: true
      ansible.builtin.get_url:
        url: 'https://update.code.visualstudio.com/latest/linux-rpm-x64/insider'
        dest: '/root/code-insiders.rpm'
        mode: 'u=rw,go='
      when: "ansible_pkg_mgr == 'zypper'"

    - name: Install VS Code Insiders (zypper)
      become: true
      community.general.zypper:
        name: '/root/code-insiders.rpm'
        state: present
        disable_gpg_check: true
      when: "ansible_pkg_mgr == 'zypper'"

    - name: Install extension cli dependencies (zypper)
      become: true
      community.general.zypper:
        name:
          - libX11-xcb1
          - libxshmfence1
        state: present
      when: ansible_pkg_mgr == 'zypper'

    - name: Install extension to be uninstalled (code)
      tags:
        # Suppress warning: [ANSIBLE0016] Tasks that run when changed should likely be handlers
        # Not applicable because this is part of the test setup not part of the role.
        - skip_ansible_lint
      become: true
      become_user: test_usr
      ansible.builtin.command: 'code --install-extension streetsidesoftware.code-spell-checker'
      changed_when: false
      when: vscode_install.changed

    - name: Install extension to be uninstalled (code-insiders)
      tags:
        # Suppress warning: [ANSIBLE0016] Tasks that run when changed should likely be handlers
        # Not applicable because this is part of the test setup not part of the role.
        - skip_ansible_lint
      become: true
      become_user: test_usr
      ansible.builtin.command: 'code-insiders --install-extension streetsidesoftware.code-spell-checker'
      changed_when: false
      when: vscode_insiders_install.changed

  roles:
    - role: ansible-role-visual-studio-code-extensions
      users:
        - username: test_usr
          visual_studio_code_extensions:
            - EditorConfig.EditorConfig
            - wholroyd.jinja
          visual_studio_code_extensions_absent:
            - streetsidesoftware.code-spell-checker
            - doesnot.Exist
        - username: test_usr2
          visual_studio_code_extensions: []
          visual_studio_code_extensions_absent: []
        - username: test_usr3
    - role: ansible-role-visual-studio-code-extensions
      visual_studio_code_extensions_build: insiders
      users:
        - username: test_usr
          visual_studio_code_extensions:
            - editorconfig.editorconfig
            - wholroyd.jinja
          visual_studio_code_extensions_absent:
            - streetsidesoftware.code-spell-checker
            - doesnot.Exist
        - username: test_usr2
          visual_studio_code_extensions: []
          visual_studio_code_extensions_absent: []
        - username: test_usr3
