---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-visual-studio-code-extensions-opensuse
    image: opensuse/leap:15.3

provisioner:
  name: ansible

verifier:
  name: testinfra
  directory: ../default/tests
