---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-visual-studio-code-extensions-ubuntu-min
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

verifier:
  name: testinfra
  directory: ../default/tests
