---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-visual-studio-code-extensions-ubuntu-xenial
    image: ubuntu:16.04
  - name: ansible-role-visual-studio-code-extensions-opensuse-leap
    image: opensuse:42.2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
